# Development profile
feature_flags:
  RAG_ENABLED: true
  ENABLE_LIVE_SEARCH: true
  EVALUATORS_ENABLED: true
  MODEL_ROUTING_ENABLED: false
  SAFETY_ENABLED: false
  PROVENANCE_ENABLED: true
  TELEMETRY_ENABLED: false
budgets:
  max_total_usd: 1.0
rag:
  top_k: 5
