version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    environment:
      - RAG_ENABLED=${RAG_ENABLED:-false}
    ports:
      - "8501:8501"
    volumes:
      - .dr_rd:/app/.dr_rd
    env_file:
      - .env
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    environment:
      - RAG_ENABLED=${RAG_ENABLED:-false}
    ports:
      - "8000:8000"
    volumes:
      - .dr_rd:/worker/.dr_rd
    env_file:
      - .env
volumes:
  drrd:
    driver: local
