[tool.black]
line-length = 88
# Omit target-version to avoid mismatches; Black will infer from runtime.
include = '\.pyi?$'
extend-exclude = '''
  build/
  |dist/
  |\.venv/
  |venv/
  |\.eggs/
  |.*\.egg-info/
'''

[tool.isort]
profile = "black"

[tool.flake8]
max-line-length = 100

[tool.flake8.per-file-ignores]
"core/agents/base_agent.py" = ["E731", "E501"]
"core/orchestrator.py" = ["E501"]
