name: Bug Report
description: File a bug report
title: "[Bug] "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What's wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues
        - label: I can reproduce with latest main
