from __future__ import annotations
from typing import Protocol, Dict, Any
from pathlib import Path


class Hook(Protocol):
    def on_iteration(self, state: Dict[str, Any]) -> None: ...
    def on_complete(self, metrics: Dict[str, Any], outputs_dir: Path | None) -> None: ...
    def on_failure(self, metrics: Dict[str, Any], outputs_dir: Path | None) -> None: ...
