# Static model assignments to reduce cost in DR-RD
# Stage/role models are configured via config.model_routing defaults.

AGENT_MODEL_MAP = {
    "Planner": "gpt-5",
    "CTO": "gpt-5",
    "Research": "gpt-5",
    "Research Scientist": "gpt-5",
    "Mechanical Systems Lead": "gpt-5",
    "Materials & Process Engineer": "gpt-5",
    "Chemical & Surface Science Specialist": "gpt-5",
    "Quantum Optics Physicist": "gpt-5",
    "Nonlinear Optics / Crystal Engineer": "gpt-5",
    "Optical Systems Engineer": "gpt-5",
    "Mechanical & Precision-Motion Engineer": "gpt-5",
    "Photonics Electronics Engineer": "gpt-5",
    "Photonic Electronics Engineer": "gpt-5",
    "Electronics & Embedded Controls Engineer": "gpt-5",
    "Software / Image-Processing Specialist": "gpt-5",
    "Fluorescence / Biological Sample Expert": "gpt-5",
    "Systems Integration & Validation Engineer": "gpt-5",
    "Data Scientist / Analytics Engineer": "gpt-5",
    "Regulatory & Compliance Lead": "gpt-5",
    "Regulatory": "gpt-5",
    "Finance": "gpt-5",
    "Prototyping & Test Lab Manager": "gpt-5",
    "Project Manager / Principal Investigator": "gpt-5",
    "Product Manager / Translational Lead": "gpt-5",
    "AI R&D Coordinator": "gpt-5",
    "Synthesizer": "gpt-5",
    "Marketing Analyst": "gpt-5",
    "IP Analyst": "gpt-5",
    "Marketing": "gpt-5",
    "IP": "gpt-5",
}

