# Static model assignments to reduce cost in DR-RD

AGENT_MODEL_MAP = {
    "Planner": "o3-deep-research",
    "CTO": "o3-deep-research",
    "Research": "o3-deep-research",
    "Research Scientist": "o3-deep-research",
    "Mechanical Systems Lead": "o3-deep-research",
    "Materials & Process Engineer": "o3-deep-research",
    "Chemical & Surface Science Specialist": "o3-deep-research",
    "Quantum Optics Physicist": "o3-deep-research",
    "Nonlinear Optics / Crystal Engineer": "o3-deep-research",
    "Optical Systems Engineer": "o3-deep-research",
    "Mechanical & Precision-Motion Engineer": "o3-deep-research",
    "Photonics Electronics Engineer": "o3-deep-research",
    "Photonic Electronics Engineer": "o3-deep-research",
    "Electronics & Embedded Controls Engineer": "o3-deep-research",
    "Software / Image-Processing Specialist": "o3-deep-research",
    "Fluorescence / Biological Sample Expert": "o3-deep-research",
    "Systems Integration & Validation Engineer": "o3-deep-research",
    "Data Scientist / Analytics Engineer": "o3-deep-research",
    "Regulatory & Compliance Lead": "o3-deep-research",
    "Regulatory": "o3-deep-research",
    "Finance": "o3-deep-research",
    "Prototyping & Test Lab Manager": "o3-deep-research",
    "Project Manager / Principal Investigator": "o3-deep-research",
    "Product Manager / Translational Lead": "o3-deep-research",
    "AI R&D Coordinator": "o3-deep-research",
    "Synthesizer": "o3-deep-research",
    "Marketing Analyst": "o3-deep-research",
    "IP Analyst": "o3-deep-research",
    "Marketing": "o3-deep-research",
    "IP": "o3-deep-research",
}
