email:
  enabled: true
  pattern: '\b[\w.+-]+@[\w.-]+\.[a-zA-Z]{2,}\b'
  token: '[REDACTED:EMAIL]'
phone:
  enabled: true
  pattern: '\b(?:\d{3}[ -]?){2}\d{4}\b'
  token: '[REDACTED:PHONE]'
ssn:
  enabled: true
  pattern: '\b\d{3}-\d{2}-\d{4}\b'
  token: '[REDACTED:SSN]'
credit_card:
  enabled: true
  pattern: '\b(?:\d[ -]?){13,16}\b'
  token: '[REDACTED:CREDIT_CARD]'
ipv4:
  enabled: true
  pattern: '\b(?:\d{1,3}\.){3}\d{1,3}\b'
  token: '[REDACTED:IPV4]'
ipv6:
  enabled: true
  pattern: '\b(?:[0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}\b'
  token: '[REDACTED:IPV6]'
street_address:
  enabled: true
  pattern: '\b\d+\s+[A-Za-z0-9.\s]+\b'
  token: '[REDACTED:ADDRESS]'
person_name:
  enabled: true
  pattern: '\b[A-Z][a-z]+\s[A-Z][a-z]+\b'
  token: '[REDACTED:NAME]'
