from config.feature_flags import *  # noqa: F401,F403

EVAL_THRESHOLD = 0.75
COVERAGE_THRESHOLD = 0.55
MAX_LAPS = 1

AGENT_HRM_ENABLED = True
AGENT_TOPK = 3
AGENT_MAX_RETRIES = 1
AGENT_THRESHOLD = 0.75

RUN_SOFT_TIME_LIMIT_SEC = 300
