name: Build Docker Images
on:
  push:
    branches: ["main"]
  tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        if: env.GHCR_USERNAME != '' && env.GHCR_TOKEN != ''
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ env.GHCR_TOKEN }}
      - name: Build app image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.app
          platforms: linux/amd64,linux/arm64
          push: ${{ env.GHCR_USERNAME != '' && env.GHCR_TOKEN != '' }}
          tags: ghcr.io/${{ env.GHCR_USERNAME }}/dr-rd-app:latest
      - name: Build worker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.worker
          platforms: linux/amd64,linux/arm64
          push: ${{ env.GHCR_USERNAME != '' && env.GHCR_TOKEN != '' }}
          tags: ghcr.io/${{ env.GHCR_USERNAME }}/dr-rd-worker:latest
