name: CI Docs

on:
  push:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
          pip install markdown-link-check
      - name: Link check
        run: markdown-link-check docs/INDEX.md
      - name: Lint docs
        run: python -m scripts.lint_docs
