name: CI

on:
  push:
  pull_request:

jobs:
  supply-chain:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    env:
      AUDIT_ALLOW_HIGH: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Ensure reports directory
        run: mkdir -p reports
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.lock.txt
          pip install --require-hashes -r dev-requirements.lock.txt
      - name: License scan
        run: |
          pip-licenses --format=json --output-file reports/licenses.json
          python scripts/check_licenses.py --input reports/licenses.json
      - name: Vulnerability audit
        run: |
          pip-audit -r requirements.lock.txt --format json --output reports/pip-audit.json || true
          python scripts/gate_pip_audit.py --input reports/pip-audit.json
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python }}
          path: reports
          if-no-files-found: ignore
