name: CI

on:
  push:
  pull_request:

jobs:
  supply-chain:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    env:
      AUDIT_ALLOW_HIGH: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Ensure report directories
        run: mkdir -p reports sbom
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --require-hashes -r requirements.lock.txt
          pip install --require-hashes -r dev-requirements.lock.txt
      - name: License scan
        run: |
          pip-licenses --format=json --output-file reports/licenses.json
          python scripts/check_licenses.py --input reports/licenses.json
      - name: Vulnerability audit
        run: |
          pip-audit -r requirements.lock.txt --format json --output reports/pip-audit.json || true
          python scripts/gate_pip_audit.py --input reports/pip-audit.json
      - name: Generate SBOM
        run: python scripts/gen_sbom.py
      - name: Reproducibility report
        run: python scripts/repro_check.py || true
      - name: Stale code scan
        run: python scripts/stale_code_scan.py --json-output reports/stale_code.json
      - name: Upload stale code report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: stale-code-${{ matrix.python }}
          path: reports/stale_code.json
          if-no-files-found: ignore
      - name: Unused dependency scan
        run: python scripts/unused_deps_scan.py --json-output reports/unused_deps.json
      - name: Upload unused dependency report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unused-deps-${{ matrix.python }}
          path: reports/unused_deps.json
          if-no-files-found: ignore
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python }}
          path: reports
          if-no-files-found: ignore
      - name: Upload SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ matrix.python }}
          path: sbom
          if-no-files-found: ignore

  tests-lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.lock.txt -r dev-requirements.lock.txt
      - run: pytest -q
      - run: mypy dr_rd
      - run: ruff dr_rd
      - run: gitleaks detect --source .
