name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: Validate config lock
        run: python scripts/validate_config_lock.py
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Type check
        if: hashFiles('mypy.ini') != ''
        run: mypy dr_rd core app
      - name: Security audit
        run: pip-audit -r requirements.txt || true
      - name: Tests
        run: pytest -q --maxfail=1 --disable-warnings
      - name: Coverage
        run: pytest --cov=dr_rd --cov=core --cov=app --cov-report=xml
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python }}
          path: |
            coverage.xml
            pytest-report.html
          if-no-files-found: ignore
