name: e2e
on:
  pull_request: {}
  workflow_dispatch: {}
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r requirements-dev.txt
          python -m playwright install --with-deps chromium
      - name: Start app and run E2E
        env:
          APP_EXTERNAL: "0"
          APP_BASE_URL: "http://localhost:8501"
          APP_START_CMD: "streamlit run app.py --server.port 8501 --server.headless true"
        run: |
          pytest -q e2e
