name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          stale-issue-label: stale
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # stale-pr-message: ''
          # stale-issue-message: ''
